[package]
name = "zulip-rs"
version = "0.1.0"
authors = ["Julian Bieber <j.bieber@patagona.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
